[package]
name = "ur-rs"
version = "0.1.0"
authors = ["Dominik Spicher <dominikspicher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "*"
phf = { version = "0.8.0", features = ["macros"] }
thiserror = "*"
