name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --all --all-targets --all-features -- -Dwarnings -D clippy::pedantic -A clippy::missing-errors-doc -A clippy::wildcard-imports -A clippy::used-underscore-binding -A clippy::cast-sign-loss -A clippy::default-trait-access
    - name: Run tests
      run: cargo test
